# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_saved_time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('is_delete', models.CharField(default=b'0', max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('shared_user', models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default=b'', max_length=5, null=True)),
                ('biography', models.CharField(default=b'', max_length=300, null=True)),
                ('avatar', models.ImageField(default=b'user-avatars/default_avatar.png', upload_to=b'user-avatars')),
                ('token', models.CharField(max_length=50, null=True)),
                ('reserve1', models.CharField(max_length=1, null=True)),
                ('reserve2', models.CharField(max_length=50, null=True)),
                ('shared_document', models.ManyToManyField(blank=True, related_name='shared_docs', to='markdown.Document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
